#!/bin/fish

# Set fish as default shell
sudo chsh -s /bin/fish $USER
export SHELL=/bin/fish

# Install fisher
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher update
