#!/bin/bash

# Install required void linux packages
sudo xbps-install -y \
	git \
	neovim \
	xorg \
	bspwm \
	sxhkd \
	kitty \
	firefox \
	rofi \
	font-firacode \
	font-awesome \
	picom \
	feh \
	curl \
	fish-shell

# Install some packages outside of xbps
# vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
