Section "InputClass"
    Identifier "libinput touchpad catchall"
    Driver "libinput"
    Option "Tapping" "true"
    Option "NaturalScrolling" "true"
    Option "MiddleEmulation" "true"
    Option "AccelSpeed" "0.6"
EndSection
