#!/bin/fish

# Catppuccin theme installation
sudo cp -r $HOME/.config/grub/catppuccin-mocha-grub-theme /usr/share/grub/themes/

# Set grub settings
echo 'GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha-grub-theme/theme.txt"' | sudo tee -a /etc/default/grub
echo 'GRUB_DISABLE_OS_PROBER=false' | sudo tee -a /etc/default/grub

# Run grub configurator
sudo grub-mkconfig -o /boot/grub/grub.cfg
